version: "3"

services:
  bright_market_backend:
    container_name: bright_market_backend
    build:
      context: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    networks:
      - webnet
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '3000:${PORT}'
    links:
      - bright_market_database
    depends_on:
      - bright_market_database
  
  bright_market_database:
    image: postgres:12.4-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: bright_market_database
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DATABASE: ${DB_NAME}

volumes:
  postgres:
networks:
  webnet: