server:
    port: 3000

db:
    type: 'postgres'
    port: 5432
    database: 'postgres'
    host: bright_market_database
    username: postgres
    password: 123456
    synchronize: true

jwt:
    expiresIn: 8600